env:
  # Determine what we need here

eks_container: &BUILD_TEMPLATE
  dockerfile: .cirrus/Dockerfile
  builder_subnet_id: ${CIRRUS_AWS_SUBNET}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t2.small
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  region: eu-central-1
  namespace: default
  docker_arguments:
    CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}

node_modules_cache_template: &NODE_MODULES_CACHE_TEMPLATE
  node_modules_cache:
    folders:
      - 'node_modules'
      - '.yarn'
    fingerprint_script: cat yarn.lock

eslint_report_cache_template: &ESLINT_REPORT_CACHE_TEMPLATE
  eslint_report_cache:
    folders:
      - "build-reports/eslint-report/**"
    fingerprint_script: echo $CIRRUS_BUILD_ID

# build_number_task:
#   eks_container:
#     <<: *BUILD_TEMPLATE
#     cpu: 1
#     memory: 2Gb
#   script:
#     - .cirrus/build-number.sh

install_dependencies_task:
  <<: *NODE_MODULES_CACHE_TEMPLATE
  timeout_in: 30m
  eks_container:
    <<: *BUILD_TEMPLATE
    cpu: 3.4
    memory: 11Gb
  script:
    - yarn install

build_task:
  <<: *NODE_MODULES_CACHE_TEMPLATE
  eks_container:
    <<: *BUILD_TEMPLATE
    cpu: 4
    memory: 4G
  depends_on:
    # - build_number
    - install_dependencies
  build_script:
    - yarn build

validation_task:
  <<: *NODE_MODULES_CACHE_TEMPLATE
  <<: *ESLINT_REPORT_CACHE_TEMPLATE
  eks_container:
    <<: *BUILD_TEMPLATE
    cpu: 4
    memory: 8G
  depends_on:
    - install_dependencies
    - build
  script:
    - yarn validate-ci
