env:
  # Determine what we need here

eks_container: &BUILD_TEMPLATE
  dockerfile: .cirrus/Dockerfile
  builder_subnet_id: ${CIRRUS_AWS_SUBNET}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t2.small
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  region: eu-central-1
  namespace: default
  docker_arguments:
    CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}

build_task:
  eks_container:
    <<: *BUILD_TEMPLATE
    cpu: 4
    memory: 8G
  build_script:
    - yarn install
    - yarn build