compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

plugins:
  - checksum: b789165b6baebadfd8a512333aba31347cd053eb357e44e1ddd961d40588164bab5a4f5375a80790045808310ebe78ec5f320817a66804d2f541ca405c2bb67c
    path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: "https://yarnplugins.com/echo-execute"

progressBarStyle: simba

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.9.1.cjs
nodeLinker: pnp