/*
 * Echoes React
 * Copyright (C) 2023-2025 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
import { Badge } from "../components/badges/Badge"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/3bo9DCW9JD52Lc21Fcyea8/-0.22.0-Echoes--Components?node-id=10415%3A5128",
  {
    props: {
      iconLeft: figma.boolean("iconLeft",{
        true: figma.instance('↳ icon'),
        false: undefined,
      }),
      label: figma.string("changeContent"),
      size: figma.enum("size", {
        small: "small",
        medium: "medium",
      }),
      isHighContrast: figma.boolean("highContrast"),
      type: figma.enum("type", {
        neutral: "neutral",
        info: "info",
        warning: "warning",
        danger: "danger",
        success: "success",
        highlight: "highlight",
      }),
      isInteractive: figma.boolean("isInteractive"),
    },
    example: (props) => 
      <Badge
        iconLeft={props.iconLeft}
        isHighContrast={props.isHighContrast}
        isInteractive={props.isInteractive}
        size={props.size}
        type={props.type}
      >
        {props.label}
      </Badge>,
  },
)
