/*
 * Echoes React
 * Copyright (C) 2023-2025 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

import figma from '@figma/code-connect';
import { Button } from '@sonarsource/echoes-react';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,

  'https://www.figma.com/design/3bo9DCW9JD52Lc21Fcyea8/-0.22.0-Echoes--Components?node-id=3562%3A8192',

  {
    props: {
      children: figma.string('label'),

      isLoading: figma.boolean('isLoading'),

      prefix: figma.boolean('hasPrefix', {
        false: undefined,
        true: figma.instance('↳ prefix'),
      }),

      size: figma.enum('size', {
        large: 'large',
        medium: 'medium',
      }),

      suffix: figma.boolean('hasSuffix', {
        false: undefined,
        true: figma.instance('↳ suffix'),
      }),

      variety: figma.enum('variety', {
        'danger ghost': 'danger-ghost',
        'danger secondary': 'danger-outline',
        'default ghost': 'default-ghost',
        'primary ghost': 'primary-ghost',
        danger: 'danger',
        default: 'default',
        primary: 'primary',
      }),
    },

    example: ({ children, ...props }) => <Button {...props}>{children}</Button>,
  },
);
