/*
 * Echoes React
 * Copyright (C) 2023-2025 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
import { Popover } from "../components/popover/Popover"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Popover,
  "https://www.figma.com/design/3bo9DCW9JD52Lc21Fcyea8/-0.22.0-Echoes--Components?node-id=3597%3A2907",
  {
    props: {
      hasSlot: figma.boolean("hasSlot", {
        true: figma.instance('↳ 🔄  extraContent'),
        false: undefined,
      }),
      hasDescription: figma.boolean("hasDescription"),
      hasFooter: figma.boolean("hasFooter"),
      trigger: figma.instance("🔄 trigger"),
      hasTitle: figma.boolean("hasTitle"),
      isOpen: figma.boolean("isOpen"),
      side: figma.enum("side", {
        bottom: "bottom",
        top: "top",
        right: "right",
        left: "left",
      }),
    },
    example: (props) => <Popover 
      extraContent={props.extraContent}
      hasDescription={props.hasDescription}
      hasFooter={props.hasFooter}
      hasSlot={props.hasSlot}
      hasTitle={props.hasTitle}
      isOpen={props.isOpen}
      side={props.side}
      trigger={props.trigger}
    />,
  },
)
