import React from "react"
import { HelperText } from "./HelperText"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  HelperText,
  "https://www.figma.com/design/3bo9DCW9JD52Lc21Fcyea8/-0.22.0-Echoes--Components?node-id=326%3A139",
  {
    props: {
      changeText: figma.string("↳ changeText"),
    },
    example: (props) => <HelperText />,
  },
)
