import React from "react"
import { Label } from "./Label"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Label,
  "https://www.figma.com/design/3bo9DCW9JD52Lc21Fcyea8/-0.22.0-Echoes--Components?node-id=325%3A139",
  {
    props: {
      required: figma.boolean("required"),
      text: figma.string("Text"),
      type: figma.enum("type", {
        default: "default",
        disabled: "disabled",
      }),
    },
    example: (props) => <Label />,
  },
)
