name: Publish on NPM

on:
  release:
    types:
      - published

jobs:
  publish:
    permissions:
      id-token: write # required for SonarSource/vault-action-wrapper
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      NPM_REPOSITORY: "sonarsource-npm-public"
      SCOPE: "@sonarsource"
      PACKAGE: "echoes-react"
    steps:
      - name: Vault
        id: secrets
        uses: SonarSource/vault-action-wrapper@d1c1ab4ca5ad07fd9cdfe1eff038a39673dfca64  # tag=2.4.2-1
        with:
          secrets:
            development/kv/data/repox url | repox_url;
            development/artifactory/token/SonarSource-echoes-react-qa-deployer access_token  | qa_deployer_access_token;
            development/artifactory/token/SonarSource-echoes-react-promoter access_token  | promoter_access_token;
            development/kv/data/npmjs sonartech_npm_token  | npm_token;
      - name: Setup JFrog for deploy
        uses: SonarSource/jfrog-setup-wrapper@eb712d76540e5d1f3756303f30387657fb204e52  # tag=2.4.1-1
        with:
          jfrogAccessToken: ${{ fromJSON(steps.secrets.outputs.vault).qa_deployer_access_token }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: mv .github/workflows/.npmrc .npmrc
      - name: Publish npm package
        env:
          NPM_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).npm_token }}
        run: |
          jfrog npm-config --repo-resolve npm --repo-deploy sonarsource-npm-public-qa
          npm publish
          jfrog npm-publish --build-name=echoes-react --build-number=${{ github.event.release.tag_name }}
          jfrog rt build-publish echoes-react ${{ github.event.release.tag_name }}
      - name: Promote npm package
        env:
          PROMOTER_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).promoter_access_token }}
          REPOX_URL: ${{ fromJSON(steps.secrets.outputs.vault).repox_url }}
        run: |
<<<<<<< Updated upstream
          jfrog rt build-promote --access-token $PROMOTER_TOKEN --url $REPOX_URL --status it-passed echoes-react ${{ github.event.release.tag_name }} sonarsource-npm-public-builds
          jfrog rt build-promote --access-token $PROMOTER_TOKEN --url $REPOX_URL --status released echoes-react ${{ github.event.release.tag_name }} sonarsource-npm-public-releases
=======
          jfrog rt bpr --access-token $PROMOTER_TOKEN --url $REPOX_URL --status it-passed echoes-react ${{ github.event.release.tag_name }} sonarsource-npm-public-builds
          jfrog rt bpr --access-token $PROMOTER_TOKEN --url $REPOX_URL --status released echoes-react ${{ github.event.release.tag_name }} sonarsource-npm-public-releases
>>>>>>> Stashed changes
