name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        required: false

jobs:
  release:
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@78fbbb684c2ebb36a682b9d66b1eda8a2eebd9b2 # 5.17.2
    with:
      publishToNpmJS: true
      skipJavascriptReleasabilityChecks: true # Temporary, until the releasability version check handles an `rc` suffix
    permissions:
      id-token: write
      contents: write
