name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        required: false

jobs:
  release:
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@f42df91661e3f3e6d81d92e86c88edd073dc1264 # 5.12.0
    with:
      publishToNpmJS: true
      skipJavascriptReleasabilityChecks: true # Temporary, until the releasability version check handles an `rc` suffix
    permissions:
      id-token: write
      contents: write
