name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        required: false

jobs:
  release:
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@96b41900898b276ffc689d4bd89271d875608bcc # 5.10.3
    with:
      publishToNpmJS: true
    permissions:
      id-token: write
      contents: write