name: Releasability status

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - master
      - branch-*
  workflow_dispatch:

jobs:
  releasability-status:
    name: Releasability status
    runs-on: sonar-xs-public
    permissions:
      id-token: write
      statuses: write
      contents: read
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
