name: Slack Notifications
on:
  check_suite:
    types: [completed]

permissions:
  contents: read
  checks: read
  id-token: write

jobs:
  slack-notifications:
    if: >-
      github.event.check_suite.head_branch == 'main' ||
      startsWith(github.event.check_suite.head_branch, 'branch-')
    runs-on: sonar-xs-public
    steps:
      - name: Send Slack Notification
        env:
          GITHUB_TOKEN: ${ github.token }
        uses: SonarSource/gh-action_slack-notify@v1
        with:
          slackChannel: ops-sonarcloud-webapp
